
Nola

Make the following 4x7 array called nola that starts with 1 and steps by 2. However, note that the first element in each row is always 4 more than the last element in the previous row.

[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]




In [5]:
import numpy as np


#Create an empty array


arr = np.zeros((4,7), dtype = int)

start = 1
for i in range(4):

  arr[i] = np.arange(start, start + 14 ,2)
  start = arr[i][-1] + 4

print(arr)



[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]
