
High School Reunion

With your high school reunion fast approaching, you decide to get in shape and lose some weight . You record your weight every day for five weeks starting on a Monday.

import numpy as np

dailywts = 185 - np.arange(5*7)/5

print(dailywts)
# [185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
#  182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
#  180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]
     


In [ ]:
import numpy as np


dailywts = 185 - np.arange(5*7)/5

print(dailywts)
#

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [ ]:
weightByWeek = dailywts.reshape(5,7);
print(weightByWeek)

[[185.  184.8 184.6 184.4 184.2 184.  183.8]
 [183.6 183.4 183.2 183.  182.8 182.6 182.4]
 [182.2 182.  181.8 181.6 181.4 181.2 181. ]
 [180.8 180.6 180.4 180.2 180.  179.8 179.6]
 [179.4 179.2 179.  178.8 178.6 178.4 178.2]]


In [ ]:
#Average Weight each week

weeklyAverage = np.array([])
for week in weightByWeek:
    print(week.mean())
    weeklyAverage = np.append(weeklyAverage,week.mean())






184.4
183.0
181.6
180.2
178.8


In [ ]:
#Average weight loss per Week

WeightLoss = np.array([])

for weeks in weightByWeek:
    dailyLoss = np.diff(weeks)
    avg_loss = dailyLoss.mean()
    WeightLoss = np.append(WeightLoss,avg_loss)

print(WeightLoss)



[-0.2 -0.2 -0.2 -0.2 -0.2]
