Define a roux array as a 1-D array such that, when it's reversed, it represents the sequence of square numbers 1, 4, 9, 16, ... with 0s interwoven between them.

Examples

# roux array of length 5
[9 0 4 0 1]

# roux array of length 8
[ 0 16  0  9  0  4  0  1]

# roux array of length 12
[ 0 36  0 25  0 16  0  9  0  4  0  1]


In [8]:
import numpy as np


arrLength = input("How long do you want the array to be ? : ")
arrLength = int(arrLength)
arr = np.zeros(arrLength, dtype=int)


counter = 1
for i in range(arrLength):

    if i % 2 == 0:
      arr[i] = counter*counter

      counter += 1


print(arr)

How long do you want the array to be ? : 10
[ 1  0  4  0  9  0 16  0 25  0]
